server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pigeon?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.hermite.repeater.pigeon.model
  configuration:
    map-underscore-to-camel-case: true
