server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pigeon?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:tkmapper/*.xml
  type-aliases-package: top.hermite.repeater.pigeon.core.model
  configuration:
    map-underscore-to-camel-case: true
